name: Lint Runner

on:
  workflow_dispatch:
  pull_request:

jobs:
  run-lint:
    name: Run Lint
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download node_modules artifact
        uses: actions/download-artifact@v3
        with:
          name: node_modules
          path: node_modules

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Run lint
        run: yarn lint

      - name: Lint Report
        uses: dorny/test-reporter@v1
        if: success()
        with:
          name: Lint

      - name: Lint Summary
        uses: test-summary/action@v2
        with:
          paths: 'reports/lint.xml'
