name: Type Check Runner

on:
  workflow_dispatch:
  pull_request:

jobs:
  run-typecheck:
    name: Run Type Check
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download node_modules artifact
        uses: actions/download-artifact@v3
        with:
          name: node_modules
          path: node_modules

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Run type check
        run: yarn typecheck

      - name: Type Check Report
        uses: dorny/test-reporter@v1
        if: success()
        with:
          name: Type Check

      - name: Type Check Summary
        uses: test-summary/action@v2
        with:
          paths: 'reports/typecheck.xml'
